<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>cite_httpswww.focusservices.com</name>
   <tag></tag>
   <elementGuidId>0d8dfa05-d18d-4b6a-b6ad-ed94bd37a4bb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>cite.iUh30.tjvcx</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rso']/div/div/div/div/div/div/div/div/a/div/cite</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>cite</value>
      <webElementGuid>b08329d3-44f6-4105-bedb-99fc3e3fbffc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>iUh30 tjvcx</value>
      <webElementGuid>e0544c90-ea83-4886-85a1-57daff0274d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a61206d5-61f0-4281-98f5-3b0058fa078a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>https://www.focusservices.com</value>
      <webElementGuid>c41059df-8c85-46a5-ac4d-735deebaa1f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rso&quot;)/div[@class=&quot;MjjYud&quot;]/div[@class=&quot;g&quot;]/div[@class=&quot;BYM4Nd&quot;]/div[@class=&quot;eKjLze&quot;]/div[@class=&quot;g&quot;]/div[1]/div[@class=&quot;tF2Cxc&quot;]/div[@class=&quot;yuRUbf&quot;]/a[1]/div[@class=&quot;TbwUpd NJjxre&quot;]/cite[@class=&quot;iUh30 tjvcx&quot;]</value>
      <webElementGuid>a60e990c-c3a5-4e9f-9f57-7be1306cd38b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rso']/div/div/div/div/div/div/div/div/a/div/cite</value>
      <webElementGuid>4d83d0f6-18b7-445e-afb2-9fb8e99511f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Focus Services – Beyond Expectations'])[1]/following::cite[1]</value>
      <webElementGuid>de21f979-bc96-41ab-b928-cd4103e33b78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Resultado web con vínculos a sitio'])[1]/following::cite[1]</value>
      <webElementGuid>61394c31-040f-4b93-be66-b24b758d9616</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='https://www.focusservices.com'])[2]/preceding::cite[1]</value>
      <webElementGuid>aa55ebc6-a8eb-4897-97ff-a9198b297141</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='En caché'])[1]/preceding::cite[2]</value>
      <webElementGuid>58d16f54-4eab-44ef-9232-ab774116ac34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='https://www.focusservices.com']/parent::*</value>
      <webElementGuid>b3d02718-f122-4b8e-b292-917a17bc6f67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//cite</value>
      <webElementGuid>fd42927c-aaf0-4d8a-9409-2861acc5c68e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//cite[(text() = 'https://www.focusservices.com' or . = 'https://www.focusservices.com')]</value>
      <webElementGuid>02c02d05-0f77-4a93-849d-fbdb49d6ca23</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
