<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Central America</name>
   <tag></tag>
   <elementGuidId>d047b2c0-88a1-4c81-a6ad-60d5c297b8c0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='av-tab-section-1']/div/div/a[2]/span[2]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>8dd83d94-eef0-42fb-b38b-57938ef57ef3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>av-inner-tab-title</value>
      <webElementGuid>ee28c2d1-24d4-4393-8531-fe85216ab070</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Central America</value>
      <webElementGuid>a444dd29-13d6-4830-a4bd-0db649030b1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;av-tab-section-1&quot;)/div[@class=&quot;av-tab-section-outer-container&quot;]/div[@class=&quot;av-tab-section-tab-title-container avia-tab-title-padding-small&quot;]/a[@class=&quot;av-section-tab-title av-tab-no-icon av-tab-with-image noHover&quot;]/span[@class=&quot;av-outer-tab-title&quot;]/span[@class=&quot;av-inner-tab-title&quot;]</value>
      <webElementGuid>713654b4-a2cf-457b-926a-62579d9bbea3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='av-tab-section-1']/div/div/a[2]/span[2]/span</value>
      <webElementGuid>f7e42420-0796-4a35-96ba-0a892eb1633b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='North America'])[1]/following::span[5]</value>
      <webElementGuid>ada5abec-d4fb-43d2-bd1d-c002fa7640fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Asia'])[1]/preceding::span[4]</value>
      <webElementGuid>5f62d13f-4d84-4854-9aa5-de4174551074</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='United States'])[1]/preceding::span[10]</value>
      <webElementGuid>363370ae-dcc2-4c1c-b975-071370f9b325</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Central America']/parent::*</value>
      <webElementGuid>ba8a91be-0a92-421f-8cf5-7692fb72fa35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]/span[2]/span</value>
      <webElementGuid>767483c7-6135-4595-a8d6-623e1f060ad4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Central America' or . = 'Central America')]</value>
      <webElementGuid>1ec189bb-5924-41c5-8f1d-f9d8c203f2a6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
