<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Now Hiring</name>
   <tag></tag>
   <elementGuidId>f323cf23-3f63-41dc-926b-fd4b27d1967d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='text-4']/div/p/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>706cfc10-9c93-4e4b-980a-1e7b59678d89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>avia-button av-icon-on-hover avia-icon_select-yes-right-icon avia-color-custom avia-size-medium avia-position-left </value>
      <webElementGuid>eaf59817-5bba-4bfc-8656-b43e31c88791</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.focusservices.com/apply/</value>
      <webElementGuid>2cead15b-1562-4f38-9baf-f71596cebdc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Now Hiring!</value>
      <webElementGuid>eef41017-d5e7-40e4-b124-89bc4ed4f2b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;text-4&quot;)/div[@class=&quot;textwidget&quot;]/p[1]/a[@class=&quot;avia-button av-icon-on-hover avia-icon_select-yes-right-icon avia-color-custom avia-size-medium avia-position-left&quot;]</value>
      <webElementGuid>cae7af40-15f7-4359-a048-db5f6fb2aae9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='text-4']/div/p/a</value>
      <webElementGuid>941b6b98-1f00-4725-96ac-62ef277adc53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Careers'])[2]/following::a[1]</value>
      <webElementGuid>d8799b54-2362-47a5-a9bc-f4f61641b86a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Case Studies'])[1]/following::a[1]</value>
      <webElementGuid>d09771db-9ae7-469d-aa7c-51ce6d718088</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='© Copyright 2019 - Focus Services'])[1]/preceding::a[1]</value>
      <webElementGuid>bbdb99f6-75ba-4704-b07d-4aeb8062beae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.focusservices.com/apply/')]</value>
      <webElementGuid>61981cb2-fc5f-43dd-a026-9d823a18c736</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/section/div/p/a</value>
      <webElementGuid>2fb8b27a-2880-43eb-a536-3ae5258b3109</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.focusservices.com/apply/' and (text() = 'Now Hiring!' or . = 'Now Hiring!')]</value>
      <webElementGuid>9cefb980-83d1-405d-81b4-560b24731735</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
